# Start with a base image containing Java runtime
FROM eclipse-temurin:21-jre-alpine
LABEL maintainer="miroslav.kovacevic@eng.it"
WORKDIR /app
EXPOSE 8761
ARG JAR_FILE=target/*.jar

# Add the application's jar to the container
COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java","-jar","app.jar"]
