spring.application.name=RESERVATIONS-SERVICE

server.port=8084

logging.level.org.springframework.security=DEBUG

Spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/reservations
spring.datasource.username=postgres
spring.datasource.password=postgres

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
