spring.application.name=AUTH-SERVICE

server.port=8081

logging.level.org.springframework.security=DEBUG

Spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/users
spring.datasource.username=postgres
spring.datasource.password=postgres

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

security.jwt.secret-key=2d2639cedf8eda3e362bfbb5ad390817ffe8276062a10afcf7de9d9365c22083
security.jwt.expiration-time=3600000
