spring.application.name=PHYSIO-SERVICE

server.port=8082

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}


logging.level.org.springframework.security=DEBUG

Spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/physios
spring.datasource.username=postgres
spring.datasource.password=postgres

eureka.client.service-url.defaultZone=http://localhost:8761/eureka


management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

