FROM eclipse-temurin:21-jre-alpine
LABEL maintainer="miroslav.kovacevic@eng.it"
WORKDIR /app
ENV SPRING_PROFILES_ACTIVE=container
EXPOSE 8084
ARG JAR_FILE=target/*.jar

# Add the application's jar to the container
COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java","-jar","app.jar"]
